### ISSUE TITLE
No Mapicons are displayed

### ISSUE THREAD

**Issue by derSpaddl** [testadaz/koken_mapbox#3]
My Map won't show any Pictures. As you can see here: https://theramble.rocks/map/ the map is loading fine. Also the new Json implementation seems to work for me see here: https://theramble.rocks/json/
Am i doing anything wrong or do i have to configure anything else?

**Comment by derSpaddl** [comment]
@pspoerri i think you are the active developer. Can you help?

**Comment by pspoerri** [comment]
Not sure what's wrong with your site. I tried to have a look at the diff between your page and [mine](https://gallery.pascalspoerri.ch/map/#). But other than the slight modifications to display thumbnails there's nothing that is really different.

The only thing I added were these lines:
```
$(document).ready(function(){   
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";
        //Reload the page
        location.reload(true);
    }
});
```
to get rid of the mapbox load issue described here: https://kokensupport.com/viewtopic.php?t=332

I would put a `echo(value)` or `console.log(values)` in the loading loop below. It could be that your images are filtered:
```
function recursive_load(values) {
    $.each( values.images, function( idx, value ) {
        var img = prepare_data(value);
	if ((img.cLat != 0 && img.cLng != 0) && !isNaN(img.cLng) && !isNaN(img.cLat)) {
              // ^------ Here's the place where filtering happens
 	      create_marker(img);           
	}
    });
    if (!values.hasOwnProperty('next')) {
        return;
    }
    $.getJSON( values.next, function( data ) {
	recursive_load(data);
     });
}
```

Here's some details on console logging: https://stackoverflow.com/questions/4539253/what-is-console-log .

**Comment by pspoerri** [comment]
You can also remove the if block:
```
if ((img.cLat != 0 && img.cLng != 0) && !isNaN(img.cLng) && !isNaN(img.cLat)) {
```
which filters images that do not have a latitude or longitude set.
